### ISSUE TITLE
Error in Readme

### ISSUE THREAD

**Issue by DevScherer** [yo-less/MMM-KVV#3]
When showing multiple Connections for specific lines the values have to be like this 'S1,S3' instead of 'S1,3'  👍 

linesoptional |   | Only show connections for specific lines - use commas to choose multiple lines.Example values: 'S1, 3'Note: You can use spaces when setting this parameter in order to enhance legibility.
-- | -- | --

Anyway, it works pretty well for me! Good Job

**Comment by yo-less** [comment]
Thanks man, it depends on what lines you want to see, there's a line "3" and a line "S3", both values would work but I can see how you read it, you thought the S would carry over to the 3 so I'm changing it to '3, S1' as I wanted to highlight that you can both choose the inner city lines and the lines that connect the city to the region.

**Comment by DevScherer** [comment]
Perfect :-) Thank You
