### ISSUE TITLE
More options on the KVV api side?

### ISSUE THREAD

**Issue by rs-development** [yo-less/MMM-KVV#6]
Are there any options on the API to receive more than 10 connections? Maybe connection 11-20? Or is there an option to specify the direction in the request?

I think about getting more information in one direction. Since only the next 10 lines are crawled, if they go into direction 1, no line is shown for direction 2.

Are there more options implemented in the API than you use, maybe routes?

I would like to contribute!

**Comment by rs-development** [comment]
As far as I see the API is from the company INIT. I don't know where the API Key came from but I would assume it would better fit the project to use the OpenData API from KVV itself.

https://www.kvv.de/fahrplan/fahrplaene/open-data.html

**Comment by yo-less** [comment]
As far as I can tell INIT handles all KVV tram monitoring and real-time traffic updates. The page you have referenced seems to allow third parties to sign up for an individual API key. The big question is whether that would give you access to more data. Should you decide to sign up for it, let me know if it provides you with more information than the open API the module currently uses.
I think that in its current state the module is very accessible. If you have to manually apply for an API key (especially by downloading and sigining a PDF form) it gets quite a bit harder to set up. The current module is based on the real-time departure data you can see for yourself by using https://live.kvv.de in any web browser. It has its limitations (you can only see a maximum of 10 departures) but it seems to be working relatively well.

**Comment by rs-development** [comment]
I was in contact with the KVV team yesterday because of the OpenData API Keys and they told me in their words: "Bitte beachten Sie jedoch, dass die Schnittstelle, die Sie verwenden, eigentlich nicht zur öffentlichen Verwendung freigegeben ist. [...] Die KVV.live-Schnittstelle ist Eigentum der Firma INIT, [...]." I don't know where you got the API key from. I see why getting your own API Key is a hassle, but it feels better for me than using an API that is not intended to be used like that from me with an API key I don't know where it came from.

Maybe the Plugin can be formed in a way the API Key from the OpenData API is used but hidden so it can not be used elsewhere.
