### ISSUE TITLE
Mixed directions on some stations

### ISSUE THREAD

**Issue by rs-development** [yo-less/MMM-KVV#7]
Using the Kolpingplatz as a stop. The results are indeed correct but the directions do not match up with the actual directions.

I curled the trams for Kolpingplatz:

Route 3 and S1 have direction 2 if going towards the central train station but route 4 has direction 1 going towards the central station.

[trams.txt](https://github.com/yo-less/MMM-KVV/files/3694860/trams.txt)

Maybe someone can doublecheck.

**Comment by rs-development** [comment]
So it is not a bug, more a feature. Each line has it's own dedicated direction. So I would consider the direction setup as not working. It may be correct on some stations but it is not guaranteed.

**Comment by yo-less** [comment]
Thanks for your comment, it entirely depends on the tram line as you have already noted, this might be related to the way the lines are set up internally when they get planned. Basically it looks like line 3 is considered to have Tivoli as its starting point whereas for line 4 it's the other way round. In other words, if you decide you want to monitor a specific direction you have to find out what number (1 or 2) KVV uses for that direction on the line you are interested in.
